---
general:
  cpiApiServiceKeyCredentialsId: "integration-suite-service-key"
  integrationFlowId: "Test_Tenant"
stages:
  Upload:
    enabled: true
  Deploy:
    enabled: true
  Integration Test:
    enabled: false

